services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent_forge
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3337:3000"
    command: ["sh", "-c", "npm start"]